### ISSUE TITLE
[react] Throw exception on undo action

### ISSUE THREAD

**Issue by nguyenngoclongdev** [nocode-js/sequential-workflow-designer#100]
Reproduce:
1. Access the demo page for react: https://nocode-js.github.io/sequential-workflow-designer/react-app/
2. In the designer, I add the step to workflow
3. Click undo button, throw bellow exception:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at e.value (https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:170191)
    at https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:170856
    at e.handler (https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:170872)
    at e.value (https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:155447)
    at e.value (https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:155616)
    at https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:155934
    at https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:154814
    at Array.forEach (<anonymous>)
    at e.value (https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:154786)
    at https://nocode-js.github.io/sequential-workflow-designer/react-app/static/js/main.63aec97b.js:2:155093
```

![Peek 2023-10-25 16-31](https://github.com/nocode-js/sequential-workflow-designer/assets/43560378/1e226b9a-f8d4-426f-96c0-aac706651ffe)

**Comment by b4rtaz** [comment]
Hello @nguyenngoclongdev! Thanks for reporting. Please check the latest version ([0.16.10](https://github.com/nocode-js/sequential-workflow-designer/releases/tag/v0.16.10)), the bug should be fixed.
